services:
  # DATABASES, ADMIN VIEWERS AND STUFF

  mysql1:
    image: mysql:8.0
    container_name: author-db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_DATABASE=author-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    volumes:
      - ./data/mysql1:/var/lib/mysql1
      - ./data/init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-uuser",
          "-ppwd",
          "-h",
          "localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: PhpMyAdmin
    links:
      - mysql1
    restart: always
    ports:
      - 5013:80
    environment:
      - PMA_ARBITRARY=1

  # API GATEWAY

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: always
    depends_on:
      - author-service
    privileged: true

  # SERVICES

  author-service:
    build:
      context: ../author-service
      dockerfile: Dockerfile
    container_name: author-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - logs:/app/logs
    restart: always
    depends_on:
      mysql1:
        condition: service_healthy
    privileged: true

volumes:
  logs: