# Default Spring Profile
server.port: 8080

spring.datasource.hikari.initializationFailTimeout: 60000

server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.isaacwallace: DEBUG
    org.springframework.boot.test: DEBUG
    de.flapdoodle.embed.mongo: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

app:
  membership-service:
    host: membership-service
    port: 8080
  inventory-service:
    host: inventory-service
    port: 8080
  employee-service:
    host: employee-service
    port: 8080

---
# For prod

# For Docker
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      # uri: mongodb://user:pwd@transaction-mongodb:27017/transactions
      host: transaction-mongodb
      port: 27017
      username: user
      password: pwd
      authentication-database: admin
      database: transactions

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.mongodb.driver: DEBUG


server:
  port: 8080

---
# For Testing

spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      #      host: localhost
      port: 0 # random port for embedded MongoDB
      database: transactionsCaseTestDb
      #      username: user
      #      password: pwd
      #      authentication-database: admin

      auto-index-creation: true
logging:
  level:
    root: INFO
    com.isaacwallace: DEBUG

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5