# Default Spring Profile
server.port: 8080

spring.datasource.hikari.initializationFailTimeout: 60000

server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.isaacwallace: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
# For test

# For h2
spring:
  config:
    activate:
      on-profile: h2

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:postgresql://membership-postgres/membership-db
    username: membership-db
    password: pwd

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        auto-quote-keyword: true

    defer-datasource-initialization: true

  sql:
    init:
      platform: h2
      mode: always


---
# For prod

# For Docker
spring:
  datasource:
    url: jdbc:postgresql://membership-postgres/membership-db
    username: membership-db
    password: pwd

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      defer-datasource-initialization: true

  config:
    activate:
      on-profile: docker

  sql:
    init:
      platform: psql
      mode: always
      schema-locations: classpath:schema-psql.sql
      data-locations: classpath:data-psql.sql