# Default Spring Profile
server.port: 8080

spring.datasource.hikari.initializationFailTimeout: 60000

server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.isaacwallace: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
# For test

# For h2
spring:
  config:
    activate:
      on-profile: h2

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:library-db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        auto-quote-keyword: true

    defer-datasource-initialization: true

  sql:
    init:
      platform: h2
      mode: always


---
# For prod

# For Docker
spring:
  datasource:
    url: jdbc:mysql://mysql1/library-db
    username: user
    password: pwd

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  config:
    activate:
      on-profile: docker

  sql:
    init:
      platform: mysql
      mode: always