services:
  membership-service:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: membership-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - logs:/app/logs
    restart: always
    depends_on:
      postgres1:
        condition: service_healthy
    privileged: true

  postgres1:
    image: postgres:latest
    hostname: postgres1
    container_name: postgres1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=membership-db
      - PGUSER=membership-db
      - POSTGRES_PASSWORD=pwd
    volumes:
      - ./data/postgres1:/var/lib/postgresql
      - ./membership-service/data/init.d:/docker-entrypoint-initdb.d
    healthcheck:
      #      test: ["CMD", "mysqladmin", "ping", "-uuser", "-ppwd", "-h", "localhost"]
      test: "pg_isready -h postgres1"
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-membership
    restart: always
    ports:
      - 9000:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=8Y2o6@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres1

volumes:
  logs: